app:
  database: "taaja"

mp:
  messaging:
    incoming:
      raw-sensor-data:
        type: "smallrye-kafka"
        bootstrap:
          servers: "193.26.156.80:9092"
        value:
          deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
    outgoing:
      raw-spatial-sensor-data:
        type: "smallrye-kafka"
        bootstrap:
          servers: "193.26.156.80:9092"
        value:
          serializer: "org.apache.kafka.common.serialization.StringSerializer"



quarkus:
  http:
    port: 8093
    cors: true
  swagger-ui:
    always-include: true
  mongodb:
    connection-string: mongodb://taaja-mongodb:27017


"%dev":
  app:
    database: "dev-taaja"

  #Mongo Config
  quarkus:
    swagger-ui:
      always-include: true
    mongodb:
      connection-string: mongodb://localhost:27017

"%test":
  app:
    database: "test-taaja"

  #Mongo Config
  quarkus:
    mongodb:
      connection-string: mongodb://localhost:27017
